name: Node.js Assignment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Run Prettier Check
      run: npx prettier --check src

    # Checks ESLint rules (fails if custom configurations are broken)
    - name: Run ESLint Verification
      run: npm run lint

    # Runs testing suite and immediately exits (CI safe mode)
    - name: Run Application Tests
      run: CI=true npm test
